### ISSUE TITLE
Geslo nima pravilne validacije

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#1]
Pri kreiranju računa zdravnika ali oskrbovanca se ne zahteva en numeričen znak.
Torej pa de test: # Preveri ustreznost gesla (najmanj 8 znakov, vsaj en numeričen)

**Comment by pavlin-policar** [comment]
Treba je preveriti, da je bo validacija potekala povsod, kjer je se preverja geslo, torej kreacija uporabnika prek admina, sprememba gesla, navadna registracija.

**Comment by grilanc** [comment]
Za prvo in zadnjo sem že uredil (ni še na gitu, zato je problem odprt). Bom dodal še k spremembi gesla.
