### ISSUE TITLE
Končna predstavitev: Premalo pacientov

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#101]
Trenutno imamo smao 7 pacientov, vendar je pod zahtevami napisano, da jih potrebujemo vsaj 10. Vprašanje tudi kako je z zobozdravniki in osebnimi zdravniki.

**Comment by lavrinec** [comment]
pa treba je imet 5 nedokončanih registracij

**Comment by lavrinec** [comment]
evo zdej je:
10 potrjenih pacientov
1 izbrisan
4 nepotrjeni
12 med sester
10 zobarjev
10 zdravnikov
