### ISSUE TITLE
Nastavitve nadzorne plošče za aktiviranega userja se ne shrani

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#103]
Če aktiviraš oskrbovanega uporabnika in mu spremeniš nastavitve nadzorne plošče se nastavitve shranijo prijavljenemu uporabniku in ne aktiviranemu uporabniku.

**Comment by lavrinec** [comment]
sklepam da je potem enako, če gre zdravnik urejat osebne podatke pacienta... bo treba še preverit
