### ISSUE TITLE
Tabela diet generira nek čuden link

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#104]
1. Nadzorna plošča > Diete zavihek
2. Klikneš na link, ki se nahaja v tabeli v stolpcu "Podatki o dietah"
3. Link je napačen

Link, ki se generira vsebuje ves tekst v celici in nima dejanskega URLja.

e.g .http://tpo-zdravstveni-is.herokuapp.com/check/Dieta%20je%20eden%20temeljev%20zdravljenja%20kroni%C4%8Dne%20ledvi%C4%8Dne%20bolezniPri%20kroni%C4%8Dni%20ledvi%C4%8Dni%20bolezni%20je%20primerna%20prehrana%20eden%20od%20temeljev%20zdravljenja%20bolezni,%20saj%20lahko%20s%20primerno%20dieto%20upo%C4%8Dasnimo%20napredovanje%20bolezni%20oziroma%20zmanj%C5%A1amo%20kopi%C4%8Denje%20odve%C4%8Dnih%20snovi%20in%20vode,%20ki%20ostajajo%20v%20telesu,%20%C4%8De%20so%20ledvice%20%C5%BEe%20prenehale%20delovati%20in%20se%20bolnik%20zdravi%20z%20dializo.V%20razli%C4%8Dnih%20obdobjih%20razvoja%20kroni%C4%8Dne%20ledvi%C4%8Dne%20bolezni%20mora%20bolnik%20upo%C5%A1tevati%20razli%C4%8Dna%20prehranska%20priporo%C4%8Dila,%20prav%20tako%20na%20na%C4%8Din%20prehranjevanja%20vplivajo%20druge%20bolezni,%20ki%20jih%20morebiti%20ima%20bolnik.%20Zato%20poznamo%20razli%C4%8Dne%20ledvi%C4%8Dne%20diete.%20Ledvice%20imajo%20pomembno%20vlogo%20pri%20presnovi%20kalija,%20natrija,%20kalcija,%20vitamina%20D,%20fosforja%20in%20vode.%20Nepravilno%20delovanje%20ledvic%20spremeni%20presnovo%20teh%20snovi,%20zato%20je%20treba%20z%20dieto%20uravnavati,%20koliko%20teh%20snovi%20lahko%20bolnik%20v%20razli%C4%8Dnih%20fazah%20bolezni%20zau%C5%BEije.

**Comment by urko94** [comment]
fixed
