### ISSUE TITLE
kreiranje odmora

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#115]
Če zdravniku kreiram odmor, medicinski sestri na profilu piše kot da je to njen prihajajoči pregled: http://puu.sh/pmId4/6959c607f3.png
le kaj pregledujeta skupaj med odmorom?

**Comment by grilanc** [comment]
Sem danes našel že en identičen bug (in ga odpravil). Stvar ni filtrirala odmorov. Sedaj jih.
