### ISSUE TITLE
Če je zdravnik zafilan, se ne pokaže lastnim pacientom

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#14]
_Ločen od #13 zaradi pomembnosti._

Če sem pacient pri doktorju, ki ne sprejema novih pacientov, ga ne vidim v select boxih, zato mi ne pusti zamenjati samo enega izmed dohtarjov.

http://puu.sh/ohXBg/4decb359a0.png

**Comment by pavlin-policar** [comment]
Tole je bilo že dolgo nazaj odpravljeno, oz. cannot reproduce.

Testirano za primer pavlin.g.p@gmail.com::password in doctor001@zis.si::password, kjer ima doktor 3 paciente in jaz kot pavlin ga še vedno lahko vidim in

**Comment by lavrinec** [comment]
Pri zobozdravnikih pa očitno ni tako. Glej doctor007@zis.si ki ima  Zobni Dohtar, http://puu.sh/pdTaW/b49585f910.png v nastavitvah pa ga ni: http://puu.sh/pdTc6/adcd758a66.png
http://puu.sh/pdTcy/8c538b8366.png

**Comment by pavlin-policar** [comment]
My mistake, bom popravil

**Comment by pavlin-policar** [comment]
Cannot reproduce.

**Comment by pavlin-policar** [comment]
Težava je bila v samih uporabnikih in njihovih podatkih, not really a bug.
