### ISSUE TITLE
Password reseti ne delajo

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#15]
Očitno smo enkrat ven vrgli (ali pa je sploh nismo imeli) migracijo za password resets, in zato to ne deluje.

**Comment by lavrinec** [comment]
ja #10 smo pustil drugač za naslednji sprint, ampak če jo zdele nardiš si lh ure pol v naslednjem pišeš

**Comment by pavlin-policar** [comment]
Aja, mislil sem, da pridejo avtomatsko s frameworkom. Samo zato.

**Comment by lavrinec** [comment]
sj pomoje pride, sam vklučil nismo... A si ti vkluču zdej?

**Comment by pavlin-policar** [comment]
Ne, nič se nisem dotikal.

**Comment by lavrinec** [comment]
zgodba predčasno narejena
