### ISSUE TITLE
številka zz

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#18]
številka zz lahko vsebuje črke in druge znake, kar ni ok

**Comment by pavlin-policar** [comment]
A to kje posebej piše da ni kul?

**Comment by lavrinec** [comment]
ponavad je to številka, sicer lh pustimo, če se tip kej spremeni

**Comment by lavrinec** [comment]
očitno sem se motu, pri številki zz in pri številkah zdravnika ali pri številki medicinske sestre je še vedno ta problem: http://puu.sh/peccD/a845ca7dce.png

**Comment by lavrinec** [comment]
Še vedno ni rešeno: http://puu.sh/petna/36b27c342f.png

**Comment by pavlin-policar** [comment]
Tole bom šel popravljati ta teden, ker si ne upam it spreminjat toliko blizu predstavitvi. Tole zahteva večje popravke.

**Comment by lavrinec** [comment]
problem je enak pri številki zdravnika, ki niti ne sme biti enaka številki medicinske sestre
