### ISSUE TITLE
mail oskrbljenca

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#19]
V primeru da oskrbljenca registriramo z mailom, ki je že v bazi, dobimo sledečo napako: http://puu.sh/oikOJ/8f20590fb1.png

**Comment by lavrinec** [comment]
enako je s številko zz

**Comment by pavlin-policar** [comment]
Rešitev je [tukaj](https://laravel.com/docs/5.1/validation#rule-unique).

**Comment by lavrinec** [comment]
je že uštimano: http://puu.sh/pcTrl/f65d63e036.png
