### ISSUE TITLE
šibko geslo dohtarja

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#20]
dohtar ma lh geslo s samimi črkami

**Comment by grilanc** [comment]
A lahko nekdo doda tole v UserAdminController, v vrstico 64, na koncu pogojev za validacijo gesla:
`|regex:/^(?=.*[\d,.;:]).+$/\'`

Bi jaz, pa imam nekaj dodatne kode že v te datoteki in je ne upam commitat, ker ni dokončana. Je blo pa to že narejeno in mi ni čisto jasno, kam je izginilo.
