### ISSUE TITLE
Not found exception when appointment is removed

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#25]
Create error pages when appointment is deleted and can not be found.

To kar se je zgodilo na vajah, imaš dashboard odprt, en ti vmes zbriše termin, ti klikneš link => error.

**Comment by grilanc** [comment]
Vprašanje: ne gre tu za klasičen 404 error? Ker za to je zgleda nekdo že napisal custom error message, če prav vidim.

EDIT: nvm, ne vidim prav :D

**Comment by grilanc** [comment]
Dodal 404.blade.php.

**Comment by lavrinec** [comment]
še tele mogoče: http://puu.sh/pcVCG/2017480b32.png ?

**Comment by grilanc** [comment]
Dodan 403.blade.php :)
