### ISSUE TITLE
Napačen ID v showUser, ko pregledujemo pacienta

### ISSUE THREAD

**Issue by grilanc** [pavlin-policar/TPO-zdravstveni-is#32]
Prijava z doctor007@zis.si, nakar klikneš na njegovega edinega pacienta (Marko). Koledar je po aktivaciji izpisoval doktorjeve dogodke, namesto pacientovih. Po preverjanju showUser vrednosti sem ugotovil, da je noter shranjen doktorjev ID (namesto pacientovega).

**Comment by lavrinec** [comment]
odpravljeno
