### ISSUE TITLE
Zdravnik zdravnika lahko vidi njegove paciente

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#33]
Če je nekdo (doctor007) doktor od drugega doktorja (doctor1), potem lahko ta (doctor007) vidi preglede in podatke od (doctor1)

**Comment by urko94** [comment]
mislim, da je sedaj napaka odpravljena ( vrne error 403 unauthorized)

**Comment by lavrinec** [comment]
ne drži, če grem js prek doctor1 kot doktor na profil svojga pacienta, ki je doktor, mi kaže vse pacienta od pacienta, kr ni glih varno: http://puu.sh/oOWf7/0a58f9d781.png

**Comment by lavrinec** [comment]
Problem je že v seznamu, ki se po mojem mnenju nebi smev videt

**Comment by urko94** [comment]
Zdaj ne vidi seznama
