### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#34]
klikniv sem na enega od pregledov iz seznama prihajajočih pregledov pri doctor007 in mi je vrglo error: http://puu.sh/oMR1D/ab6110befc.png

**Comment by grilanc** [comment]
A je tole mogče rezultat ročnega popravljanja v bazi? Če prav vidim, so bili vnosi pred kratkim sicer spet resetirani.

**Comment by lavrinec** [comment]
ok bom zapru, pa če se pojav jutr ko bom testirov, pa bom novga odpru
