### ISSUE TITLE
Sprostitev termina

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#41]
sprostitev termina vrže error: http://puu.sh/oOdAY/a67d5233b2.png

**Comment by grilanc** [comment]
Popravljeno. Btw, zaradi zgornjega screenshota sem uspel popravit še en major bug. Ko je zdravnik prijavil zdravnika na pregled, se je kot 'doctor' in 'patient' shranil enak ID, kar je seveda neumnost, posledično pa je bil problem tudi v dvojnem izpisovanju takega zasedenega termina.
