### ISSUE TITLE
vnos šifrantov ne deluje več

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#43]
http://puu.sh/oOet2/73ed63cc05.png

**Comment by pavlin-policar** [comment]
To se zgodi samo, ko sta "minimalna" in "maksimalna" vrednost prazni. Drugače vnos deluje pravilno.

Sumljivo je to, da v sql queriju proba vstavt prazne vrednosti.

**Comment by pavlin-policar** [comment]
**#TODO Remove test entries from "sex" code type to avoid _offending_ the ppl**
