### ISSUE TITLE
Sprosti termin ne deluje

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#46]
Če sprostim termin, se termin ne sprosti!

**Comment by lavrinec** [comment]
Treba je samo dopisati, zakaj ga ni sprostilo

**Comment by grilanc** [comment]
Kot kaže je tale reč že spisana in dejansko deluje. Sem pozabil, da sem že dodal obvestilo. Zdaj sta dve možnosti: 
1. morda obvestila prej nismo opazili, 
2. morda pa obstaja nek robni pogoj, ko se obvestilo sploh ne pojavi.
<img src="http://s32.postimg.org/618uhhnud/Obvestilo.png">
Zaenkrat bom issue označil kot zaprt. Če se pojavi robni primer, se lahko issue ponovno odpre.
