### ISSUE TITLE
vnos meritev

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#56]
Meritve, ki sem jih vnesel kot doktor ali medicinska sestra, mi jih zazna kot da jih je vnesel pacient.
Prav tako bi bilo bolje, da bi v tabeli zgoraj namesto doktor pisalo izvajalec meritve.
http://puu.sh/pa8PU/c628b89346.png

**Comment by urko94** [comment]
zdaj prikaze osebo, ki je vnesla meritev
