### ISSUE TITLE
pooblastitev medicinske sestre

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#57]
Medicinska sestra se nahaja v bolnišnici v kopru: http://puu.sh/pa93c/5ca67d86e7.png
Prav tako doktor: http://puu.sh/pa961/cc7c2edb04.png
Doktor nima medicinske sestre na seznamu za pooblastitev: http://puu.sh/pa96F/4a4638614f.png !

**Comment by grilanc** [comment]
Popravljeno. Query zdaj išče medicinske sestre glede na inštitucije v Doctor tabeli. Tabela nurses_institutions ni več potrebna.
