### ISSUE TITLE
sprostitev medicinske sestre

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#62]
pri doktorju na nadzorni plošči ob kliku na svojo medicinsko sestro: http://puu.sh/pa9S6/8a46ffa521.png
se ta samodejno brez opozorila sprosti, kar zna biti moteče za uporabnike, ki sistema ne poznajo

**Comment by grilanc** [comment]
Popravljeno. Sedaj ime ni več link, poleg imena pa je opcija za sprostitev [Sprosti osebo]. Poskusil sem uporabiti class btn-primary, a je izgledalo grdo, tako da gre zdaj kar za navaden link. Če zna kdo polepšati, please do.
