### ISSUE TITLE
koledar medicinske sestre

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#65]
Medicinska sestra si lahko ustvari svoj urnik in na njem na črno izvaja preglede pacientov: http://puu.sh/pcViW/1bcaff3d7b.png

**Comment by grilanc** [comment]
V tretje gre rado? :D Sedaj sem z Miroslavom Mogočnim uspešno ustvaril urnik doktorice Ane.
