### ISSUE TITLE
meritve na nadzorni plošči

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#66]
meritve na nadzorni plošči bi morale biti izpisane zadnje in ne prve, pa tudi vrstni red bi moral biti ravno obrnjen: http://puu.sh/pcVTP/b08ae9f76d.png
torej manjkajo meritve vnešene med danes in 21.5

**Comment by urko94** [comment]
zdaj izpiše zadnje meritve v pravilnem vrstnem redu
