### ISSUE TITLE
Dodajanje zdravnika ne dela (admin)

### ISSUE THREAD

**Issue by pavlin-policar** [pavlin-policar/TPO-zdravstveni-is#67]
![](https://i.gyazo.com/8366f6c19fdf7b178c50a266cdd06858.png)
![](https://i.gyazo.com/e6c36679f397744df4e33f62cc78da71.png)

Vendar ima očitno nek vpliv na DB, ker če hočem še enkrat dat isto, mi napiše da mail že obstaja v DB.

**Comment by pavlin-policar** [comment]
Tudi ko želim urejati profil ustvarjenega zdravnika iz nedokončanih registracij, dobim podoben error:

![](https://i.gyazo.com/56aecd119918122804de7aab72f0ac46.png)

**Comment by grilanc** [comment]
On it.

**Comment by grilanc** [comment]
Problem je bil v uporabi Auth::user(), v primeru, ko je šlo za admina. Do user IDja se sedaj dostopa preko \Request::url(), ker je očitno to edini način, kako v ViewServiceProviderju priti do pravega IDja.
