### ISSUE TITLE
error page

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#69]
Te errorji: http://puu.sh/pe7kN/f98927ba69.png bi bili lahko 404 ali pa bi biv vsaj debug mode izključen

**Comment by grilanc** [comment]
Sem pogledal, če se da nekako preusmeriti query exceptione na 404 stran, a žal ne najdem nič konkretnega.

**Comment by lavrinec** [comment]
@pavlin-policar je rešu
