### ISSUE TITLE
urejanje meritev

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#84]
pacient si lahko priredi rezultate meritev, ki jih je vnesla medicinska sestra:
http://puu.sh/peb2L/4ccdf634b4.png

**Comment by urko94** [comment]
napaka odpravljena. Sedaj lahko meritve ureja samo tista oseba, ki jih je vnesla.

**Comment by lavrinec** [comment]
lahko pa jih briše, kar pa tudi ne vem če je vredu

**Comment by lavrinec** [comment]
ubistvu je to potem že problem #80
