### ISSUE TITLE
pacienti medicinske sestre

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#86]
filtriranje po tabeli medicinske sestre ne deluje uredu, če bi bilo 50 pacientov bi bila to velika težava:
http://puu.sh/pebKD/20db31fb0f.png

**Comment by grilanc** [comment]
Fixed.

**Comment by lavrinec** [comment]
žov ne drži: http://puu.sh/pefwK/2f876a05df.png
v tabeli jih je 5 ne 3, zih kkšn html error še not: http://puu.sh/pefyN/7f57ed0f6e.png

**Comment by grilanc** [comment]
Napaka je bila v postavitvi <tbody> tagov. Kar je skoraj hujše, kot pozabljen zaklepaj...
