### ISSUE TITLE
napaka grafa

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#90]
zahteval sem meritve nadskupine nova meritev, ki vsebuje telesno temperaturo in srčni utrip, a so se na grafu prikazali podatki krvnega tlaka: http://puu.sh/pee9x/91fb4338a9.png

**Comment by urko94** [comment]
Na grafu so se prikazale mertve telesne temperature. Graf je omejen na od 30 do 50, zato srčnega utripa ni na grafu. To sem že popravil, samo še push-am.
