### ISSUE TITLE
kreiranje profila

### ISSUE THREAD

**Issue by lavrinec** [pavlin-policar/TPO-zdravstveni-is#92]
kreiranje profila po registraciji ne deluje: http://puu.sh/peplI/7228e04918.jpg

**Comment by grilanc** [comment]
Napaka je v CreateProfileRequest, v vrstici z
`'email' => 'required|email|unique:users,email,' . $this->route('user')->id`

Verjetno ga moti tisti user id (trying to access property of non-object). Če ne bo nikomur uspelo do jutri popravit, lahko magar vržemo ven preverjanje unique idja, vsaj začasno.

**Comment by lavrinec** [comment]
http://puu.sh/per3p/69f3b524ab.png

**Comment by lavrinec** [comment]
ja problem je ker ne dobi id od uporabnika...
